read config file from rake tests to set disable verify peer correctly
onc-healthit/inferno-program pull request #296
Opened 2021-05-26 21:28 UTC by hershilpatel

# Summary
Updating running tests from tasks.rake so it reads the config file

## New behavior
Now tasks.rake manually reads the config file to learn about verify_peer

## Code changes

## Testing guidance
Change the config's disable_verify_peer Run inferno tests from rake to test and confirm that USCCAP-01 is ommited

2021-06-02 16:48 UTC, arscan requested changes

2021-06-02 16:48 UTC, arscan commented on lib/tasks/tasks.rake
> +    disable_verify_peer = config['disable_verify_peer']
Manually reading config file seems brittle.  I did some searching around how to leverage the work Sinatra is already doing here and came across a [SO question/answer with an example](https://stackoverflow.com/questions/36507763/how-to-access-sinatra-custom-settings-from-service) which led me to:

```
Inferno::App::Endpoint.settings.disable_verify_peer
```
That seems to work for me.  Have you tried this?

2021-06-02 16:57 UTC, arscan commented
I came across a pretty easy way to leverage Sinatra's built in config parsing, instead of separately re-reading the config file as is done here.  Since @hershilpatel is out this week, I've made the change.  FYI @okeefm -- do you see any downside to this alternate approach?

2021-06-03 12:49 UTC, okeefm approved these changes
Works for me; if I change the value in `config.yml`, I see it change in `tasks.rake` if I pry into it.

2021-06-03 13:01 UTC, okeefm commented
I can't think of any particular downsides. I think the code in `Inferno::App::Endpoint` is already getting executed either way, since we require it, so it's not like there's any side-effects that weren't already happening.

2021-06-04 17:22 UTC, arscan approved these changes

2021-06-04 17:22 UTC, merged