FI-1308: deprecate BED-04/05
onc-healthit/inferno-program pull request #349
Opened 2021-08-23 16:49 UTC by yunwwang

# Summary
This PR addresses Github Issue #279 

BDE-04 and BDE-05 are client requirements and should not be tested using server's responses

## New behavior
Deprecate BDE-04 and BDE-05

## Code changes

## Testing guidance
Verify that Multi Patient Group Compartment Export Tests does not include BDE-04 and BDE-05

2021-08-23 18:05 UTC, Jammjammjamm requested changes
This looks fine except that it seems to add a python submodule.

2021-08-23 18:12 UTC, yunwwang commented
That py file is strange.

2021-08-23 19:17 UTC, Jammjammjamm approved these changes

2021-08-31 14:58 UTC, czh-orz approved these changes

2021-08-31 17:11 UTC, merged